// Structural Home language only. Project facts are resolved from the canonical registry.
export const homeCopy = {
  en: {
    eyebrow: "Independent studio · Barcelona",
    hero: ["Products.", "Systems.", "Worlds."],
    intro: "Product engineering meets creative technology. Software, controlled AI and spatial experiences — built with intention.",
    explore: "Explore the ecosystem", start: "Start a conversation", index: "Studio ecosystem",
    mapTitle: "One studio.\nConnected territories.",
    mapIntro: "From useful software to immersive worlds. Six ways into the same practice.",
    center: "One connected practice", chamberHint: "Explore a territory",
    chambers: [
      ["Products", "Tools with a point of view"],
      ["Research / Infrastructure", "The systems behind the work"],
      ["Games / Interactive Worlds", "Authored places to inhabit"],
      ["Work / Evidence", "Ideas made tangible"],
      ["Immersive / Spatial", "Beyond the flat screen"],
      ["Commercial / Collaboration", "Build something together"],
    ],
    products: "Studio products", productsTitle: "Useful by design.\nDistinct by nature.",
    productsIntro: "Independent tools, shaped around real workflows. A closer look at what we are building.",
    case: "Explore the case", proof: "Open live proof", evidence: "Selected evidence",
    evidenceTitle: "The thinking,\nmade visible.", archive: "Explore all work",
    spatial: "Immersive / Spatial", spatialTitle: "A different\nsense of presence.",
    spatialIntro: "Photography, interfaces and interaction become spaces to enter.", immersive: "Explore immersive work",
    research: "Research / Infrastructure", researchTitle: "What makes\nthe system work.",
    researchBody: "Controlled AI systems, agent infrastructure and internal production tools. Explicit tools, evaluation and human review give the work its structure.",
    researchTerms: ["Control", "Evaluation", "Orchestration"],
    worlds: "Games / Interactive Worlds", worldsTitle: "Worlds with\ntheir own logic.",
    worldsBody: "An ongoing studio territory: authored worlds, real-time systems and game technology. A space for interaction, simulation and visual direction.",
    worldsNote: "An evolving practice", closing: "Commercial / Collaboration",
    closingTitle: "What should\nwe build next?", closingBody: "A product. An interactive system. An immersive experience. Bring the ambition; we will shape the path together.",
    offer: "Explore ways to work together", top: "Back to the opening",
  },
  es: {
    eyebrow: "Estudio independiente · Barcelona",
    hero: ["Productos.", "Sistemas.", "Mundos."],
    intro: "Ingeniería de producto y tecnología creativa. Software, IA controlada y experiencias espaciales — construidos con intención.",
    explore: "Explorar el ecosistema", start: "Iniciar una conversación", index: "Ecosistema del estudio",
    mapTitle: "Un estudio.\nTerritorios conectados.",
    mapIntro: "Del software útil a los mundos inmersivos. Seis formas de entrar en una misma práctica.",
    center: "Una práctica conectada", chamberHint: "Explorar un territorio",
    chambers: [
      ["Productos", "Herramientas con criterio propio"],
      ["Investigación / Infraestructura", "Los sistemas detrás del trabajo"],
      ["Juegos / Mundos interactivos", "Lugares de autor para habitar"],
      ["Trabajo / Evidencia", "Ideas que toman forma"],
      ["Inmersivo / Espacial", "Más allá de la pantalla"],
      ["Servicios / Colaboración", "Construir algo juntos"],
    ],
    products: "Productos del estudio", productsTitle: "Útiles por diseño.\nPropios por naturaleza.",
    productsIntro: "Herramientas independientes para flujos de trabajo reales. Una mirada a lo que estamos construyendo.",
    case: "Explorar el caso", proof: "Abrir demo pública", evidence: "Evidencia seleccionada",
    evidenceTitle: "El pensamiento\nse hace visible.", archive: "Explorar todo el trabajo",
    spatial: "Inmersivo / Espacial", spatialTitle: "Otra forma\nde estar presente.",
    spatialIntro: "La fotografía, las interfaces y la interacción se convierten en espacios que explorar.", immersive: "Explorar el trabajo inmersivo",
    research: "Investigación / Infraestructura", researchTitle: "Lo que sostiene\nal sistema.",
    researchBody: "Sistemas de IA controlados, infraestructura de agentes y herramientas internas de producción. Herramientas explícitas, evaluación y revisión humana dan estructura al trabajo.",
    researchTerms: ["Control", "Evaluación", "Orquestación"],
    worlds: "Juegos / Mundos interactivos", worldsTitle: "Mundos con\nsu propia lógica.",
    worldsBody: "Un territorio del estudio en evolución: mundos de autor, sistemas en tiempo real y tecnología de juegos. Un espacio para la interacción, la simulación y la dirección visual.",
    worldsNote: "Una práctica en evolución", closing: "Servicios / Colaboración",
    closingTitle: "¿Qué construimos\na continuación?", closingBody: "Un producto. Un sistema interactivo. Una experiencia inmersiva. Trae la ambición; daremos forma al camino juntos.",
    offer: "Explorar cómo colaborar", top: "Volver al inicio",
  },
} as const;
